### ISSUE TITLE
Ошибка обработки чека

### ISSUE THREAD

**Issue by croacker** [croacker/s-irk-buyers-club#136]
03:30:01.025 [reactor-http-epoll-3] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at jdk.proxy2/jdk.proxy2.$Proxy145.save(Unknown Source)
        at com.croacker.buyersclub.service.OrganizationServiceImpl.save(OrganizationServiceImpl.java:60)
        at com.croacker.buyersclub.service.OfdCheckServiceImpl.saveOrganization(OfdCheckServiceImpl.java:110)
        at com.croacker.buyersclub.service.OfdCheckServiceImpl.process(OfdCheckServiceImpl.java:54)
        at com.croacker.buyersclub.service.telegram.TelegramFileServiceImpl.lambda$processChecks$4(TelegramFileServiceImpl.java:157)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.croacker.buyersclub.service.telegram.TelegramFileServiceImpl.processChecks(TelegramFileServiceImpl.java:161)
        at com.croacker.buyersclub.service.telegram.TelegramFileServiceImpl.lambda$processFile$0(TelegramFileServiceImpl.java:54)
..................................
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "name" violates not-null constraint
  Detail: Failing row contains (339, null, null, null, 2023-06-07 03:30:00.893242, 2023-06-07 03:30:00.893242, f).

**Comment by croacker** [comment]
[{"_id":"646de9e4d29e38b41f01971d","createdAt":"2023-05-24T10:41:40+00:00","ticket":{"document":{"receipt":{"cashTotalSum":0,"code":3,"creditSum":0,"dateTime":"2023-05-23T20:42:00","ecashTotalSum":14999,"fiscalDocumentFormatVer":4,"fiscalDocumentNumber":23428,"fiscalDriveNumber":"9960440302336055","fiscalSign":4051913036,"fnsUrl":"www.nalog.gov.ru","items":[{"name":"Печенье LOTTE CHOCOPIE ПРОСЛОЕННОЕ ГЛАЗИРОВАННОЕ 336Г","nds":1,"ndsSum":2500,"paymentType":4,"price":14999,"productType":1,"productCodeDataError":"not supported product type 3","quantity":1,"sum":14999}],"kktRegId":"0006646401053151    ","nds18":2500,"operationType":1,"operator":"Горохов Вадим Алексеевич","operatorInn":"381611557460","prepaidSum":0,"provisionSum":0,"requestNumber":209,"retailPlace":"магазин Бристоль","retailPlaceAddress":"664022, г Иркутск, ул 25 Октября, д. 20, помещение 137","shiftNumber":229,"taxationType":1,"appliedTaxationType":1,"totalSum":14999,"user":"ООО \"Альбион-2002\"","userInn":"5257056036  "}}}}]
